apiVersion: v1
kind: Service
metadata:
  name: ${DEPLOYMENT_NAME}-service
  namespace: ${NAMESPACE}
  labels:
    app: ${DEPLOYMENT_NAME}
    cosign-demo: "true"
spec:
  selector:
    app: ${DEPLOYMENT_NAME}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP