name: cosign-keyless-wiz-demo

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:

permissions:
  id-token: write     # needed for keyless signing
  contents: read
  packages: write

env:
  REGISTRY: ${{ vars.REGISTRY || 'ghcr.io' }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME || 'cosign-keyless-wiz-nginx' }}

jobs:
  build-push-sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker login (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build image
        id: build
        run: |
          IMAGE_REF=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.ref_name || 'manual' }}
          docker build \
            -t "$IMAGE_REF" \
            -f kavedarr/examples/cosign-keyless-wiz/Dockerfile \
            kavedarr/examples/cosign-keyless-wiz
          echo "IMAGE_REF=$IMAGE_REF" >> $GITHUB_OUTPUT

      - name: Push image
        run: docker push "${{ steps.build.outputs.IMAGE_REF }}"

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Keyless sign via GitHub OIDC (Fulcio)
        env:
          COSIGN_YES: "true"
        run: |
          cosign sign \
            "${{ steps.build.outputs.IMAGE_REF }}"

      - name: Verify with issuer + repo identity (defense-in-depth)
        run: |
          cosign verify \
            --certificate-oidc-issuer https://token.actions.githubusercontent.com \
            --certificate-identity-regexp "^https://github.com/${{ github.repository }}/.*$" \
            "${{ steps.build.outputs.IMAGE_REF }}"

      - name: Install wizcli (CI)
        run: |
          curl -fsSL -o wizcli https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64
          chmod +x wizcli

      - name: Wiz CLI auth (uses repo secrets)
        env:
          WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
          WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
          WIZ_TENANT_URL: ${{ secrets.WIZ_TENANT_URL }}
        run: ./wizcli auth

      # Placeholder: add Wiz ImageTrust checks/apply as desired.
      - name: Wiz ImageTrust placeholder
        run: echo "Integrate wizcli imagetrust apply/validate here."

