name: ecr-copy-unsigned

on:
  workflow_dispatch:
    inputs:
      source_image:
        description: "Upstream image to copy (e.g., docker.io/library/alpine:3.20)"
        required: true
        default: "docker.io/library/alpine:3.20"
      ecr_repo:
        description: "ECR repository name (will be created if missing)"
        required: true
        default: "cosigndemo-unsigned"
      tag:
        description: "Tag to use in ECR"
        required: true
        default: "unsigned-manual"
      aws_region:
        description: "AWS region"
        required: true
        default: "us-east-1"

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ github.event.inputs.aws_region }}
      SOURCE_IMAGE: ${{ github.event.inputs.source_image }}
      ECR_REPO: ${{ github.event.inputs.ecr_repo }}
      TAG: ${{ github.event.inputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get AWS account ID
        id: sts
        run: echo "account_id=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_OUTPUT

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Ensure ECR repo exists
        run: |
          aws ecr describe-repositories --repository-names "$ECR_REPO" >/dev/null 2>&1 || \
          aws ecr create-repository --repository-name "$ECR_REPO" >/dev/null

      - name: Copy upstream image to ECR (UNSIGNED)
        id: push
        run: |
          set -euo pipefail
          ECR_URI=${{ steps.sts.outputs.account_id }}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}
          docker pull "$SOURCE_IMAGE"
          docker tag  "$SOURCE_IMAGE" "$ECR_URI:$TAG"
          docker push "$ECR_URI:$TAG"
          echo "image_ref=$ECR_URI:$TAG" >> $GITHUB_OUTPUT
          echo "ECR unsigned image: $ECR_URI:$TAG" >> $GITHUB_STEP_SUMMARY
