name: eks-deploy

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: "AWS region (ECR/EKS)"
        required: true
        default: "us-east-1"
      cluster_name:
        description: "EKS cluster name"
        required: true
        default: "cosign-demo"
      ecr_repo:
        description: "ECR repository name (created if missing)"
        required: true
        default: "cosigndemo-nginx"
      source_image:
        description: "Upstream image to copy (e.g., docker.io/library/alpine:3.20)"
        required: true
        default: "docker.io/library/alpine:3.20"
      tag:
        description: "Tag to apply to the image"
        required: true
        default: "manual"
      namespace:
        description: "Kubernetes namespace"
        required: true
        default: "demo"
      deployment_name:
        description: "Deployment name"
        required: true
        default: "nginx"
      sign:
        description: "Sign image with AWS KMS?"
        type: boolean
        required: true
        default: true
      kms_key_ref:
        description: "KMS key alias or ARN (required if sign=true)"
        required: false

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  run:
    name: Copy → (Sign) → Deploy to EKS
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ github.event.inputs.aws_region }}
      CLUSTER_NAME: ${{ github.event.inputs.cluster_name }}
      NAMESPACE: ${{ github.event.inputs.namespace }}
      DEPLOYMENT_NAME: ${{ github.event.inputs.deployment_name }}
      SOURCE_IMAGE: ${{ github.event.inputs.source_image }}
      ECR_REPO: ${{ github.event.inputs.ecr_repo }}
      TAG: ${{ github.event.inputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get AWS account ID
        id: sts
        run: echo "account_id=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_OUTPUT

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Ensure ECR repo exists
        run: |
          aws ecr describe-repositories --repository-names "$ECR_REPO" >/dev/null 2>&1 || \
          aws ecr create-repository --repository-name "$ECR_REPO" >/dev/null

      - name: Copy upstream image to ECR
        id: push
        run: |
          set -euo pipefail
          ECR_URI=${{ steps.sts.outputs.account_id }}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}
          docker pull "$SOURCE_IMAGE"
          docker tag  "$SOURCE_IMAGE" "$ECR_URI:$TAG"
          docker push "$ECR_URI:$TAG"
          echo "image_ref=$ECR_URI:$TAG" >> $GITHUB_OUTPUT
          echo "image_uri=$ECR_URI:$TAG" >> $GITHUB_OUTPUT

      - name: Install cosign
        if: ${{ inputs.sign }}
        uses: sigstore/cosign-installer@v3

      - name: Sign with AWS KMS (optional)
        if: ${{ inputs.sign }}
        env:
          COSIGN_YES: "true"
        run: |
          if [ -z "${{ github.event.inputs.kms_key_ref }}" ]; then
            echo "kms_key_ref is required when sign=true" >&2
            exit 1
          fi
          KEY_URI="awskms:///${{ github.event.inputs.kms_key_ref }}"
          cosign sign --key "$KEY_URI" "${{ steps.push.outputs.image_ref }}"
          cosign verify --key "$KEY_URI" "${{ steps.push.outputs.image_ref }}"
          cosign public-key --key "$KEY_URI" > aws-cosign-public.pem
          echo "Saved aws-cosign-public.pem"
      
      - name: Upload public key (if signed)
        if: ${{ inputs.sign }}
        uses: actions/upload-artifact@v4
        with:
          name: aws-cosign-public
          path: aws-cosign-public.pem

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.29.0"

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name "$CLUSTER_NAME" --region "$AWS_REGION"

      - name: Render and apply manifests
        run: |
          mkdir -p rendered
          export NAMESPACE DEPLOYMENT_NAME
          export CONTAINER_NAME=${DEPLOYMENT_NAME}
          export IMAGE_REF="${{ steps.push.outputs.image_ref }}"
          envsubst < kavedarr/deploy/eks/k8s/namespace.yaml  > rendered/namespace.yaml
          envsubst < kavedarr/deploy/eks/k8s/deployment.yaml > rendered/deployment.yaml
          envsubst < kavedarr/deploy/eks/k8s/service.yaml    > rendered/service.yaml
          kubectl apply -f rendered/namespace.yaml
          kubectl apply -f rendered/deployment.yaml
          kubectl apply -f rendered/service.yaml

      - name: Wait for rollout
        run: kubectl rollout status deploy/$DEPLOYMENT_NAME -n "$NAMESPACE" --timeout=180s

